/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccination.management.system;

/**
 *
 * @author UMER
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        AddPatientRecord = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PatientInfo = new javax.swing.JButton();
        VaccineInfo = new javax.swing.JButton();
        DisplayInfo = new javax.swing.JButton();
        Certificate = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(500, 500));
//        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setVisible(false);
        panel2.setVisible(false);

        AddPatientRecord.setText("ADD PATIENT RECORD");
        AddPatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(AddPatientRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(AddPatientRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

//        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        PatientInfo.setText("PATIENT INFO");
        PatientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientInfoActionPerformed(evt);
            }
        });

        VaccineInfo.setText("VACCINE INFO");
        VaccineInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccineInfoActionPerformed(evt);
            }
        });

        DisplayInfo.setText("DISPLAY INFO");
        DisplayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayInfoActionPerformed(evt);
            }
        });

        Certificate.setText("CERTIFICATE");
        Certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CertificateActionPerformed(evt);
            }
        });

        LogIn.setText("LOG OUT");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PatientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VaccineInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Certificate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogIn)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientInfo)
                    .addComponent(VaccineInfo)
                    .addComponent(DisplayInfo)
                    .addComponent(Certificate)
                    .addComponent(LogIn))
                .addGap(0, 7, Short.MAX_VALUE))
        );

//        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 760, 30));

        jPanel3.setVisible(false);
        jPanel3.setVisible(false);

        jButton3.setText("UPDATE VACCINE RECORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

//        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayInfoActionPerformed

    private void VaccineInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccineInfoActionPerformed
                jPanel3.setVisible(true);
    }//GEN-LAST:event_VaccineInfoActionPerformed

    private void PatientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientInfoActionPerformed
        panel2.setVisible(true);
    }//GEN-LAST:event_PatientInfoActionPerformed

    private void AddPatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientRecordActionPerformed
        // TODO add your handling code here:
        panel2.setVisible(false);
        AddPatientRecord ap1 = new AddPatientRecord();
        setVisible(false);
        ap1.setVisible(true);
    }//GEN-LAST:event_AddPatientRecordActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        loginpage l1 = new loginpage();
        setVisible(false);
        l1.setVisible(true);
    }//GEN-LAST:event_LogInActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        VaccineRecord v1 = new VaccineRecord();
        v1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CertificateActionPerformed
        // TODO add your handling code here:
        Certificate c1 = new Certificate();
        setVisible(false);
        c1.setVisible(true);
    }//GEN-LAST:event_CertificateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dashboard d1 = new Dashboard();
                        d1.setVisible(true);
                d1.panel2.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientRecord;
    private javax.swing.JButton Certificate;
    private javax.swing.JButton DisplayInfo;
    private javax.swing.JButton LogIn;
    private javax.swing.JButton PatientInfo;
    private javax.swing.JButton VaccineInfo;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
