/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */








package vaccination.management.system;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author JD
 */
public class VaccineRecord extends javax.swing.JFrame {
    
    
    
     public static void VaccineInfo (String[] args) {
        
    }
    
    
    
    

    /**
     * Creates new form VaccineInfo
     */
    public VaccineRecord() {
        initComponents();
        ComBoxDisease.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComBoxDisease = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComBoxVaccine = new javax.swing.JComboBox<>();
        ButtSubmit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Spinner = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 50));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Disease");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 100, 100, 35);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vaccine Information");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-130, 30, 776, 32);

        ComBoxDisease.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComBoxDisease.setForeground(new java.awt.Color(51, 51, 51));
        ComBoxDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COVID-19", "Polio", "Hepatitis", "Chickenpox" }));
        ComBoxDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxDiseaseActionPerformed(evt);
            }
        });
        jPanel1.add(ComBoxDisease);
        ComBoxDisease.setBounds(10, 140, 90, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Vaccine");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 100, 100, 35);

        ComBoxVaccine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComBoxVaccine.setForeground(new java.awt.Color(51, 51, 51));
        ComBoxVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxVaccineActionPerformed(evt);
            }
        });
        jPanel1.add(ComBoxVaccine);
        ComBoxVaccine.setBounds(110, 140, 100, 35);

        ButtSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtSubmit.setText("Submit");
        ButtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(ButtSubmit);
        ButtSubmit.setBounds(220, 140, 100, 35);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 280, 80, 25);

        Spinner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(Spinner);
        Spinner.setBounds(430, 240, 50, 31);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 210, 70, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(90, 210, 70, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 210, 60, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 210, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 190, 60, 16);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(330, 210, 80, 20);
        jTextField5.getAccessibleContext().setAccessibleName("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Age Limit");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 190, 60, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Rec Dose");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 190, 60, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Time Durt");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 190, 60, 16);

        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(TextField);
        TextField.setBounds(420, 210, 70, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 190, 70, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Efficancy");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 190, 60, 16);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 130, 190, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ComBoxDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxDiseaseActionPerformed
       // TODO add your handling code here:
 
       try
       {
       if (ComBoxDisease.getSelectedItem().equals("Polio"))
       {TextField.setText("");
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
           jLabel4.setText("");
           ComBoxVaccine.removeAllItems();
       try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            String query = "(select Vaccine_Name from Vaccine where DID = (select DID from Disease where DID=2))";
            
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet result = statement.executeQuery();
           
            while (result.next()) {

String name=result.getString("Vaccine_Name");

ComBoxVaccine.addItem(name);
                
            
            }      
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       ComBoxVaccine.setSelectedItem(null);
       }
       
       
       
       
       else if (ComBoxDisease.getSelectedItem().equals("COVID-19")) 
       {TextField.setText("");
        jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
           jLabel4.setText("");
           jLabel4.setText("");
           ComBoxVaccine.removeAllItems();
       try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            String query = "(select Vaccine_Name from Vaccine where DID = (select DID from Disease where DID=1))";

            
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet result = statement.executeQuery();
           
            while (result.next()) {

String name=result.getString("Vaccine_Name");

ComBoxVaccine.addItem(name);
                
            
            }      
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       ComBoxVaccine.setSelectedItem(null);
       }
       
       
       
       
       else if (ComBoxDisease.getSelectedItem().equals("Hepatitis"))
       {TextField.setText("");
        jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
           jLabel4.setText("");
           jLabel4.setText("");
           ComBoxVaccine.removeAllItems();
       try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            String query = "(select Vaccine_Name from Vaccine where DID = (select DID from Disease where DID=3))";
        
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet result = statement.executeQuery();
           
            while (result.next()) {

String name=result.getString("Vaccine_Name");

ComBoxVaccine.addItem(name);
                
            
            }      
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       ComBoxVaccine.setSelectedItem(null);
       }
       
       
       
       else if (ComBoxDisease.getSelectedItem().equals("Chickenpox"))
       {TextField.setText("");
        jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
           jLabel4.setText("");
           jLabel4.setText("");
           ComBoxVaccine.removeAllItems();
       try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            String query = "(select Vaccine_Name from Vaccine where DID = (select DID from Disease where DID=4))";

            
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet result = statement.executeQuery();
           
            while (result.next()) {

String name=result.getString("Vaccine_Name");

ComBoxVaccine.addItem(name);
                
            
            }      
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       ComBoxVaccine.setSelectedItem(null);
       }
      }
       catch(Exception e)
       {
          System.out.println(e);
       }
        

       
       
       
        
    }//GEN-LAST:event_ComBoxDiseaseActionPerformed

    private void ButtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSubmitActionPerformed

        

            
            
            
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Sinopharm')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0){
           while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
                
                
                
            } 
           }
           
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
        
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Sinovac')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'CanSino')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Pfizer')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'OPV')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'IPV')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Havrix')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Engerix')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'Varivax')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity,Price,Age_Limit,Recomm_Dose,Time_Btw_Dose,Efficancy from Vaccine where Vaccine_Name = 'ProQuad')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));                
                TextField.setText(a);
                String b=String.valueOf(res.getString("Price"));                
                jTextField1.setText(b);
                 String c=String.valueOf(res.getString("Age_Limit"));                
                jTextField2.setText(c);
                String d=String.valueOf(res.getString("Recomm_Dose"));                
                jTextField3.setText(d);
                String e=String.valueOf(res.getString("Time_Btw_Dose"));                
                jTextField4.setText(e);
                String f=String.valueOf(res.getString("Efficancy"));                
                jTextField5.setText(f);
            } 
           }
     
          connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       


        
        if (ComBoxVaccine.getSelectedItem().equals("Sinopharm"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
}    
else if (ComBoxVaccine.getSelectedItem().equals("Sinovac"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("CanSino"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("Pfizer"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("OPV"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("IPV"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("Havrix"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("Engerix"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("Varivax"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 
else if (ComBoxVaccine.getSelectedItem().equals("ProQuad"))
{
    jLabel4.setText("");
    jLabel4.setText("\n Selected Disease is : " + ComBoxDisease.getSelectedItem().toString() + "\n Selected Vaccine is : " + ComBoxVaccine.getSelectedItem().toString());
           
} 


       


    }//GEN-LAST:event_ButtSubmitActionPerformed

    private void ComBoxVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxVaccineActionPerformed
       // TODO add your handling code here:
       
        
    }//GEN-LAST:event_ComBoxVaccineActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try
       {
        
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Sinopharm')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(a);
            } 
           }
           else
           {TextField.setText("");
           
           {while (res.next()) {
               
                String a=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(a);
                TextField.setText((qun+val)+"");
                
           
            } 
           
           }
      
           }
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
       
        
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Sinovac')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String a=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(a);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String a=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(a);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
        
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'CanSino')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
        
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Pfizer')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'OPV')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'IPV')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Havrix')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Engerix')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'Varivax')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }
        
         
        try {
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localHost:1433;databaseName=PersonalInfo;user=umer;password=umer6899;");
            
            
            String query = "(select Quantity from Vaccine where Vaccine_Name = 'ProQuad')";
            Statement st=connection.createStatement();
            ResultSet res =st.executeQuery(query);
            
           String value =Spinner.getValue().toString();
           int val=Integer.parseInt(value);
           if (val==0)
           {while (res.next()) {
                String s=String.valueOf(res.getString("Quantity"));
                
                TextField.setText(s);
            } 
           }
           else 
           
           {while (res.next()) {
               
                String s=String.valueOf(res.getString("Quantity"));
                int qun=Integer.parseInt(s);
                TextField.setText(""+(qun+val));
                
           
            } 
           
           }
      
           
            connection.close();
        } catch (SQLException ex) {
          ex.printStackTrace();
        }

}
       catch(Exception e)
       {
          System.out.println(e);
       }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccineRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtSubmit;
    private javax.swing.JComboBox<String> ComBoxDisease;
    private javax.swing.JComboBox<String> ComBoxVaccine;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JTextField TextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
